//
// AccessTokenCreationRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AccessTokenCreationRequest: Codable {

    public enum Scopes: String, Codable { 
        case clientSuperuser = "CLIENT_SUPERUSER"
        case clientAdmin = "CLIENT_ADMIN"
        case verifiedConsumer = "VERIFIED_CONSUMER"
        case updateProfile = "UPDATE_PROFILE"
        case oneTime = "ONE_TIME"
        case passwordReset = "PASSWORD_RESET"
        case backend = "BACKEND"
        case clientReportDownload = "CLIENT_REPORT_DOWNLOAD"
    }
    public var clientId: String?
    public var email: String?
    public var password: String?
    public var scopes: [Scopes]?
    public var durationSeconds: Int64?

    public init(clientId: String? = nil, email: String? = nil, password: String? = nil, scopes: [Scopes]? = nil, durationSeconds: Int64? = nil) {
        self.clientId = clientId
        self.email = email
        self.password = password
        self.scopes = scopes
        self.durationSeconds = durationSeconds
    }

    public enum CodingKeys: String, CodingKey { 
        case clientId = "client_id"
        case email
        case password
        case scopes
        case durationSeconds = "duration_seconds"
    }

}
