//
// AuthCodeResponseValidateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AuthCodeResponseValidateRequest: Codable {

    public var code: String?
    public var state: String?

    public init(code: String? = nil, state: String? = nil) {
        self.code = code
        self.state = state
    }


}
