//
// BuiltCampaignControllerTriggerHasPriorRewardResponseFilterMinAgeUnits.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BuiltCampaignControllerTriggerHasPriorRewardResponseFilterMinAgeUnits: Codable {

    public var duration: BuiltCampaignControllerTriggerHasPriorRewardResponseFilterMinAgeDuration?
    public var durationEstimated: Bool?
    public var dateBased: Bool?
    public var timeBased: Bool?

    public init(duration: BuiltCampaignControllerTriggerHasPriorRewardResponseFilterMinAgeDuration? = nil, durationEstimated: Bool? = nil, dateBased: Bool? = nil, timeBased: Bool? = nil) {
        self.duration = duration
        self.durationEstimated = durationEstimated
        self.dateBased = dateBased
        self.timeBased = timeBased
    }


}
