//
// BuiltCampaignControllerTriggerEventResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BuiltCampaignControllerTriggerEventResponse: Codable {

    public enum TriggerType: String, Codable { 
        case share = "SHARE"
        case purchase = "PURCHASE"
        case event = "EVENT"
        case score = "SCORE"
        case zoneState = "ZONE_STATE"
        case apiVersion = "API_VERSION"
        case referredByEvent = "REFERRED_BY_EVENT"
        case legacyQuality = "LEGACY_QUALITY"
        case expression = "EXPRESSION"
        case access = "ACCESS"
        case dataIntelligenceEvent = "DATA_INTELLIGENCE_EVENT"
        case hasPriorStep = "HAS_PRIOR_STEP"
        case maxmind = "MAXMIND"
        case rewardEvent = "REWARD_EVENT"
        case hasPriorReward = "HAS_PRIOR_REWARD"
    }
    public enum TriggerPhase: String, Codable { 
        case matching = "MATCHING"
        case qualifying = "QUALIFYING"
        case quality = "QUALITY"
    }
    public enum EventType: String, Codable { 
        case impression = "IMPRESSION"
        case legacyConsumerEvent = "LEGACY_CONSUMER_EVENT"
        case scheduled = "SCHEDULED"
        case referredBy = "REFERRED_BY"
        case input = "INPUT"
        case share = "SHARE"
        case step = "STEP"
        case identified = "IDENTIFIED"
        case referred = "REFERRED"
        case displaced = "DISPLACED"
        case displacedBy = "DISPLACED_BY"
        case _internal = "INTERNAL"
        case message = "MESSAGE"
        case dataIntelligence = "DATA_INTELLIGENCE"
        case shareable = "SHAREABLE"
    }
    public var triggerId: String?
    public var triggerType: TriggerType?
    public var triggerPhase: TriggerPhase?
    public var triggerName: String?
    public var componentReferences: [CampaignComponentReferenceResponse]?
    public var eventNames: [String]?
    public var eventType: EventType?

    public init(triggerId: String? = nil, triggerType: TriggerType? = nil, triggerPhase: TriggerPhase? = nil, triggerName: String? = nil, componentReferences: [CampaignComponentReferenceResponse]? = nil, eventNames: [String]? = nil, eventType: EventType? = nil) {
        self.triggerId = triggerId
        self.triggerType = triggerType
        self.triggerPhase = triggerPhase
        self.triggerName = triggerName
        self.componentReferences = componentReferences
        self.eventNames = eventNames
        self.eventType = eventType
    }

    public enum CodingKeys: String, CodingKey { 
        case triggerId = "trigger_id"
        case triggerType = "trigger_type"
        case triggerPhase = "trigger_phase"
        case triggerName = "trigger_name"
        case componentReferences = "component_references"
        case eventNames = "event_names"
        case eventType = "event_type"
    }

}
