//
// BuiltCampaignControllerTriggerHasPriorRewardResponseFilterMinAgeDuration.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BuiltCampaignControllerTriggerHasPriorRewardResponseFilterMinAgeDuration: Codable {

    public var seconds: Int64?
    public var zero: Bool?
    public var negative: Bool?
    public var nano: Int?

    public init(seconds: Int64? = nil, zero: Bool? = nil, negative: Bool? = nil, nano: Int? = nil) {
        self.seconds = seconds
        self.zero = zero
        self.negative = negative
        self.nano = nano
    }


}
