//
// BuiltCampaignFlowStepAppResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BuiltCampaignFlowStepAppResponse: Codable {

    public var name: String?
    public var _description: String?
    public var type: BuiltCampaignFlowStepAppTypeResponse?

    public init(name: String? = nil, _description: String? = nil, type: BuiltCampaignFlowStepAppTypeResponse? = nil) {
        self.name = name
        self._description = _description
        self.type = type
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case _description = "description"
        case type
    }

}
