//
// BuiltCampaignFlowStepMetricResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BuiltCampaignFlowStepMetricResponse: Codable {

    public var name: String?
    public var _description: String?
    public var expression: String?
    public var unit: String?
    public var tags: [String]?

    public init(name: String? = nil, _description: String? = nil, expression: String? = nil, unit: String? = nil, tags: [String]? = nil) {
        self.name = name
        self._description = _description
        self.expression = expression
        self.unit = unit
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case _description = "description"
        case expression
        case unit
        case tags
    }

}
