//
// BuiltCampaignFlowStepResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BuiltCampaignFlowStepResponse: Codable {

    public var flowStepId: String?
    public var flowPath: String?
    public var sequence: Decimal?
    public var stepName: String?
    public var iconType: String?
    public var metrics: [BuiltCampaignFlowStepMetricResponse]?
    public var apps: [BuiltCampaignFlowStepAppResponse]?
    public var tags: [String]?
    public var name: String?
    public var iconColor: String?
    public var componentReferences: [CampaignComponentReferenceResponse]?

    public init(flowStepId: String? = nil, flowPath: String? = nil, sequence: Decimal? = nil, stepName: String? = nil, iconType: String? = nil, metrics: [BuiltCampaignFlowStepMetricResponse]? = nil, apps: [BuiltCampaignFlowStepAppResponse]? = nil, tags: [String]? = nil, name: String? = nil, iconColor: String? = nil, componentReferences: [CampaignComponentReferenceResponse]? = nil) {
        self.flowStepId = flowStepId
        self.flowPath = flowPath
        self.sequence = sequence
        self.stepName = stepName
        self.iconType = iconType
        self.metrics = metrics
        self.apps = apps
        self.tags = tags
        self.name = name
        self.iconColor = iconColor
        self.componentReferences = componentReferences
    }

    public enum CodingKeys: String, CodingKey { 
        case flowStepId = "flow_step_id"
        case flowPath = "flow_path"
        case sequence
        case stepName = "step_name"
        case iconType = "icon_type"
        case metrics
        case apps
        case tags
        case name
        case iconColor = "icon_color"
        case componentReferences = "component_references"
    }

}
