//
// BuiltCampaignControllerActionEarnRewardResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BuiltCampaignControllerActionEarnRewardResponse: Codable {

    public enum ActionType: String, Codable { 
        case email = "EMAIL"
        case schedule = "SCHEDULE"
        case signal = "SIGNAL"
        case incentivize = "INCENTIVIZE"
        case shareEvent = "SHARE_EVENT"
        case fireAsPerson = "FIRE_AS_PERSON"
        case dataIntelligence = "DATA_INTELLIGENCE"
        case approve = "APPROVE"
        case decline = "DECLINE"
        case earnReward = "EARN_REWARD"
        case fulfillReward = "FULFILL_REWARD"
        case redeemReward = "REDEEM_REWARD"
        case cancelReward = "CANCEL_REWARD"
        case revokeReward = "REVOKE_REWARD"
        case stepSignal = "STEP_SIGNAL"
        case webhook = "WEBHOOK"
        case expression = "EXPRESSION"
    }
    public enum Quality: String, Codable { 
        case high = "HIGH"
        case low = "LOW"
        case always = "ALWAYS"
    }
    public var actionId: String?
    public var actionType: ActionType?
    public var quality: Quality?
    public var componentReferences: [CampaignComponentReferenceResponse]?
    public var rewardName: String?
    public var rewardSupplierId: String?
    public var pollingId: String?
    public var slots: [String]?
    public var tags: [String]?
    public var data: [String:Entry?]?
    public var programDomainId: String?
    public var sandbox: String?
    public var valueOfEventBeingRewarded: String?

    public init(actionId: String? = nil, actionType: ActionType? = nil, quality: Quality? = nil, componentReferences: [CampaignComponentReferenceResponse]? = nil, rewardName: String? = nil, rewardSupplierId: String? = nil, pollingId: String? = nil, slots: [String]? = nil, tags: [String]? = nil, data: [String:Entry?]? = nil, programDomainId: String? = nil, sandbox: String? = nil, valueOfEventBeingRewarded: String? = nil) {
        self.actionId = actionId
        self.actionType = actionType
        self.quality = quality
        self.componentReferences = componentReferences
        self.rewardName = rewardName
        self.rewardSupplierId = rewardSupplierId
        self.pollingId = pollingId
        self.slots = slots
        self.tags = tags
        self.data = data
        self.programDomainId = programDomainId
        self.sandbox = sandbox
        self.valueOfEventBeingRewarded = valueOfEventBeingRewarded
    }

    public enum CodingKeys: String, CodingKey { 
        case actionId = "action_id"
        case actionType = "action_type"
        case quality
        case componentReferences = "component_references"
        case rewardName = "reward_name"
        case rewardSupplierId = "reward_supplier_id"
        case pollingId = "polling_id"
        case slots
        case tags
        case data
        case programDomainId = "program_domain_id"
        case sandbox
        case valueOfEventBeingRewarded = "value_of_event_being_rewarded"
    }

}
