//
// CampaignControllerTriggerMaxMindResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CampaignControllerTriggerMaxMindResponse: Codable {

    public enum TriggerType: String, Codable { 
        case share = "SHARE"
        case purchase = "PURCHASE"
        case event = "EVENT"
        case score = "SCORE"
        case zoneState = "ZONE_STATE"
        case apiVersion = "API_VERSION"
        case referredByEvent = "REFERRED_BY_EVENT"
        case legacyQuality = "LEGACY_QUALITY"
        case expression = "EXPRESSION"
        case access = "ACCESS"
        case dataIntelligenceEvent = "DATA_INTELLIGENCE_EVENT"
        case hasPriorStep = "HAS_PRIOR_STEP"
        case maxmind = "MAXMIND"
        case rewardEvent = "REWARD_EVENT"
        case hasPriorReward = "HAS_PRIOR_REWARD"
    }
    public enum TriggerPhase: String, Codable { 
        case matching = "MATCHING"
        case qualifying = "QUALIFYING"
        case quality = "QUALITY"
    }
    public enum DefaultQualityScore: String, Codable { 
        case error = "ERROR"
        case low = "LOW"
        case high = "HIGH"
    }
    public var triggerId: String?
    public var triggerType: TriggerType?
    public var triggerPhase: TriggerPhase?
    public var triggerName: String?
    public var componentReferences: [CampaignComponentReferenceResponse]?
    public var defaultQualityScore: DefaultQualityScore?
    public var riskThreshold: Int64?
    public var ipThreshold: Int64?
    public var allowHighRiskEmail: Bool?

    public init(triggerId: String? = nil, triggerType: TriggerType? = nil, triggerPhase: TriggerPhase? = nil, triggerName: String? = nil, componentReferences: [CampaignComponentReferenceResponse]? = nil, defaultQualityScore: DefaultQualityScore? = nil, riskThreshold: Int64? = nil, ipThreshold: Int64? = nil, allowHighRiskEmail: Bool? = nil) {
        self.triggerId = triggerId
        self.triggerType = triggerType
        self.triggerPhase = triggerPhase
        self.triggerName = triggerName
        self.componentReferences = componentReferences
        self.defaultQualityScore = defaultQualityScore
        self.riskThreshold = riskThreshold
        self.ipThreshold = ipThreshold
        self.allowHighRiskEmail = allowHighRiskEmail
    }

    public enum CodingKeys: String, CodingKey { 
        case triggerId = "trigger_id"
        case triggerType = "trigger_type"
        case triggerPhase = "trigger_phase"
        case triggerName = "trigger_name"
        case componentReferences = "component_references"
        case defaultQualityScore = "default_quality_score"
        case riskThreshold = "risk_threshold"
        case ipThreshold = "ip_threshold"
        case allowHighRiskEmail = "allow_high_risk_email"
    }

}
