//
// CampaignStepMappingResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CampaignStepMappingResponse: Codable {

    public var _id: String?
    public var zone: CampaignStepMappingZoneResponse?
    public var creative: CreativeResponse?
    public var enabled: Bool?
    public var enabledOnStates: BuildtimeEvaluatableCampaignBuildtimeContextSetState?
    public var showEnableToggle: Bool?
    public var experienceTypes: BuildtimeEvaluatableCampaignBuildtimeContextSetCampaignExperienceType?
    public var componentReferences: [CampaignComponentReferenceResponse]?
    public var data: [StepDataResponse]?

    public init(_id: String? = nil, zone: CampaignStepMappingZoneResponse? = nil, creative: CreativeResponse? = nil, enabled: Bool? = nil, enabledOnStates: BuildtimeEvaluatableCampaignBuildtimeContextSetState? = nil, showEnableToggle: Bool? = nil, experienceTypes: BuildtimeEvaluatableCampaignBuildtimeContextSetCampaignExperienceType? = nil, componentReferences: [CampaignComponentReferenceResponse]? = nil, data: [StepDataResponse]? = nil) {
        self._id = _id
        self.zone = zone
        self.creative = creative
        self.enabled = enabled
        self.enabledOnStates = enabledOnStates
        self.showEnableToggle = showEnableToggle
        self.experienceTypes = experienceTypes
        self.componentReferences = componentReferences
        self.data = data
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case zone
        case creative
        case enabled
        case enabledOnStates = "enabled_on_states"
        case showEnableToggle = "show_enable_toggle"
        case experienceTypes = "experience_types"
        case componentReferences = "component_references"
        case data
    }

}
