//
// CampaignStepMappingZoneResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CampaignStepMappingZoneResponse: Codable {

    public var name: BuildtimeEvaluatableCampaignBuildtimeContextString?

    public init(name: BuildtimeEvaluatableCampaignBuildtimeContextString? = nil) {
        self.name = name
    }


}
