//
// CampaignLabelResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CampaignLabelResponse: Codable {

    public enum ModelType: String, Codable { 
        case program = "PROGRAM"
        case data = "DATA"
    }
    public var name: String?
    public var type: ModelType?

    public init(name: String? = nil, type: ModelType? = nil) {
        self.name = name
        self.type = type
    }


}
