//
// DataAttributeMapping.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DataAttributeMapping: Codable {

    public var attribute: String?
    public var sourceAttribute: String?
    public var defaultValue: String?

    public init(attribute: String? = nil, sourceAttribute: String? = nil, defaultValue: String? = nil) {
        self.attribute = attribute
        self.sourceAttribute = sourceAttribute
        self.defaultValue = defaultValue
    }

    public enum CodingKeys: String, CodingKey { 
        case attribute
        case sourceAttribute = "source_attribute"
        case defaultValue = "default_value"
    }

}
