//
// EventNameMatchPrehandlerConditionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Condition that checks the event name. */

public struct EventNameMatchPrehandlerConditionResponse: Codable {

    public enum ModelType: String, Codable { 
        case eventNameMatch = "EVENT_NAME_MATCH"
        case httpHeaderMatch = "HTTP_HEADER_MATCH"
        case javascriptV1 = "JAVASCRIPT_V1"
    }
    public var _id: String?
    public var type: ModelType?
    public var eventNames: [String]?

    public init(_id: String? = nil, type: ModelType? = nil, eventNames: [String]? = nil) {
        self._id = _id
        self.type = type
        self.eventNames = eventNames
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case type
        case eventNames = "event_names"
    }

}
