//
// FireAsPersonJourney.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FireAsPersonJourney: Codable {

    public enum JourneyType: String, Codable { 
        case advocate = "ADVOCATE"
        case friend = "FRIEND"
    }
    public enum ReferralReason: String, Codable { 
        case shareRecipient = "SHARE_RECIPIENT"
        case shareId = "SHARE_ID"
        case shareableId = "SHAREABLE_ID"
        case couponCode = "COUPON_CODE"
        case advocate = "ADVOCATE"
        case advocateCode = "ADVOCATE_CODE"
        case advocatePartnerUserId = "ADVOCATE_PARTNER_USER_ID"
        case displacedPartnerUserId = "DISPLACED_PARTNER_USER_ID"
        case unknownReason = "UNKNOWN_REASON"
        case incentivizedShare = "INCENTIVIZED_SHARE"
        case partnerEventId = "PARTNER_EVENT_ID"
        case partnerShareId = "PARTNER_SHARE_ID"
    }
    public var journeyType: JourneyType?
    public var referralReason: ReferralReason?
    public var couponCode: String?
    public var advocateCode: String?
    public var shareId: String?
    public var shareableId: String?
    public var channel: String?
    public var source: String?
    public var campaignId: String?
    public var container: String?
    public var label: String?
    public var reason: String?
    public var zone: String?
    public var promotableCode: String?
    public var advocatePartnerUserId: String?

    public init(journeyType: JourneyType? = nil, referralReason: ReferralReason? = nil, couponCode: String? = nil, advocateCode: String? = nil, shareId: String? = nil, shareableId: String? = nil, channel: String? = nil, source: String? = nil, campaignId: String? = nil, container: String? = nil, label: String? = nil, reason: String? = nil, zone: String? = nil, promotableCode: String? = nil, advocatePartnerUserId: String? = nil) {
        self.journeyType = journeyType
        self.referralReason = referralReason
        self.couponCode = couponCode
        self.advocateCode = advocateCode
        self.shareId = shareId
        self.shareableId = shareableId
        self.channel = channel
        self.source = source
        self.campaignId = campaignId
        self.container = container
        self.label = label
        self.reason = reason
        self.zone = zone
        self.promotableCode = promotableCode
        self.advocatePartnerUserId = advocatePartnerUserId
    }

    public enum CodingKeys: String, CodingKey { 
        case journeyType = "journey_type"
        case referralReason = "referral_reason"
        case couponCode = "coupon_code"
        case advocateCode = "advocate_code"
        case shareId = "share_id"
        case shareableId = "shareable_id"
        case channel
        case source
        case campaignId = "campaign_id"
        case container
        case label
        case reason
        case zone
        case promotableCode = "promotable_code"
        case advocatePartnerUserId = "advocate_partner_user_id"
    }

}
