//
// HttpHeaderMatchPrehandlerConditionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Condition that checks the event HTTP headers. */

public struct HttpHeaderMatchPrehandlerConditionResponse: Codable {

    public enum ModelType: String, Codable { 
        case eventNameMatch = "EVENT_NAME_MATCH"
        case httpHeaderMatch = "HTTP_HEADER_MATCH"
        case javascriptV1 = "JAVASCRIPT_V1"
    }
    public var _id: String?
    public var type: ModelType?
    public var httpHeaders: [String:[String]]?

    public init(_id: String? = nil, type: ModelType? = nil, httpHeaders: [String:[String]]? = nil) {
        self._id = _id
        self.type = type
        self.httpHeaders = httpHeaders
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case type
        case httpHeaders = "http_headers"
    }

}
