//
// MapDataAttributesPrehandlerActionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Action represented by data mappers that can change the data of the event. */

public struct MapDataAttributesPrehandlerActionResponse: Codable {

    public enum ModelType: String, Codable { 
        case setData = "SET_DATA"
        case setSandbox = "SET_SANDBOX"
        case mapDataAttributes = "MAP_DATA_ATTRIBUTES"
        case javascriptV1 = "JAVASCRIPT_V1"
    }
    public var _id: String?
    public var type: ModelType?
    public var dataAttributeMappings: [DataAttributeMapping]?

    public init(_id: String? = nil, type: ModelType? = nil, dataAttributeMappings: [DataAttributeMapping]? = nil) {
        self._id = _id
        self.type = type
        self.dataAttributeMappings = dataAttributeMappings
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case type
        case dataAttributeMappings = "data_attribute_mappings"
    }

}
