//
// PartnerEventId.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PartnerEventId: Codable {

    public var name: RuntimeEvaluatableHasPriorStepTriggerContextOptionalString?
    public var value: RuntimeEvaluatableHasPriorStepTriggerContextOptionalString?

    public init(name: RuntimeEvaluatableHasPriorStepTriggerContextOptionalString? = nil, value: RuntimeEvaluatableHasPriorStepTriggerContextOptionalString? = nil) {
        self.name = name
        self.value = value
    }


}
