//
// PersonRewardResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PersonRewardResponse: Codable {

    public var _id: String?
    public var rewardId: String?
    public var partnerRewardSupplierId: String?
    public var rewardSupplierId: String?
    public var amount: String?
    public var faceValue: String?
    public var faceValueType: String?
    public var dateIssued: Date?
    public var state: String?
    public var campaignId: String?
    public var programLabel: String?
    public var sandbox: String?
    public var partnerRewardId: String?
    public var dateEarned: Date?
    public var slots: [String]?
    public var tags: [String]?
    public var rewardName: String?
    public var valueOfRewardedEvent: Decimal?
    public var data: [String:Entry?]?
    public var expiryDate: Date?

    public init(_id: String? = nil, rewardId: String? = nil, partnerRewardSupplierId: String? = nil, rewardSupplierId: String? = nil, amount: String? = nil, faceValue: String? = nil, faceValueType: String? = nil, dateIssued: Date? = nil, state: String? = nil, campaignId: String? = nil, programLabel: String? = nil, sandbox: String? = nil, partnerRewardId: String? = nil, dateEarned: Date? = nil, slots: [String]? = nil, tags: [String]? = nil, rewardName: String? = nil, valueOfRewardedEvent: Decimal? = nil, data: [String:Entry?]? = nil, expiryDate: Date? = nil) {
        self._id = _id
        self.rewardId = rewardId
        self.partnerRewardSupplierId = partnerRewardSupplierId
        self.rewardSupplierId = rewardSupplierId
        self.amount = amount
        self.faceValue = faceValue
        self.faceValueType = faceValueType
        self.dateIssued = dateIssued
        self.state = state
        self.campaignId = campaignId
        self.programLabel = programLabel
        self.sandbox = sandbox
        self.partnerRewardId = partnerRewardId
        self.dateEarned = dateEarned
        self.slots = slots
        self.tags = tags
        self.rewardName = rewardName
        self.valueOfRewardedEvent = valueOfRewardedEvent
        self.data = data
        self.expiryDate = expiryDate
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case rewardId = "reward_id"
        case partnerRewardSupplierId = "partner_reward_supplier_id"
        case rewardSupplierId = "reward_supplier_id"
        case amount
        case faceValue = "face_value"
        case faceValueType = "face_value_type"
        case dateIssued = "date_issued"
        case state
        case campaignId = "campaign_id"
        case programLabel = "program_label"
        case sandbox
        case partnerRewardId = "partner_reward_id"
        case dateEarned = "date_earned"
        case slots
        case tags
        case rewardName = "reward_name"
        case valueOfRewardedEvent = "value_of_rewarded_event"
        case data
        case expiryDate = "expiry_date"
    }

}
