//
// PersonRelationshipResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PersonRelationshipResponse: Codable {

    public var role: String?
    public var isParent: Bool?
    public var reason: String?
    public var container: String?
    public var updatedAt: Date?
    public var otherPersonId: String?
    public var data: [String:Entry?]?

    public init(role: String? = nil, isParent: Bool? = nil, reason: String? = nil, container: String? = nil, updatedAt: Date? = nil, otherPersonId: String? = nil, data: [String:Entry?]? = nil) {
        self.role = role
        self.isParent = isParent
        self.reason = reason
        self.container = container
        self.updatedAt = updatedAt
        self.otherPersonId = otherPersonId
        self.data = data
    }

    public enum CodingKeys: String, CodingKey { 
        case role
        case isParent = "is_parent"
        case reason
        case container
        case updatedAt = "updated_at"
        case otherPersonId = "other_person_id"
        case data
    }

}
