//
// PersonShareResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PersonShareResponse: Codable {

    public var shareId: String?
    public var shareableId: String?
    public var channel: String?
    public var message: String?
    public var shareDate: Date?
    public var recipient: String?
    public var friendPersonId: String?
    public var link: String?
    public var data: [String:Entry?]?
    public var partnerId: PartnerEventIdResponse?

    public init(shareId: String? = nil, shareableId: String? = nil, channel: String? = nil, message: String? = nil, shareDate: Date? = nil, recipient: String? = nil, friendPersonId: String? = nil, link: String? = nil, data: [String:Entry?]? = nil, partnerId: PartnerEventIdResponse? = nil) {
        self.shareId = shareId
        self.shareableId = shareableId
        self.channel = channel
        self.message = message
        self.shareDate = shareDate
        self.recipient = recipient
        self.friendPersonId = friendPersonId
        self.link = link
        self.data = data
        self.partnerId = partnerId
    }

    public enum CodingKeys: String, CodingKey { 
        case shareId = "share_id"
        case shareableId = "shareable_id"
        case channel
        case message
        case shareDate = "share_date"
        case recipient
        case friendPersonId = "friend_person_id"
        case link
        case data
        case partnerId = "partner_id"
    }

}
