//
// PersonShareableResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PersonShareableResponse: Codable {

    public var code: String?
    public var key: String?
    public var label: String?
    public var link: String?
    public var personId: String?
    public var content: PersonShareableContentResponse?
    public var data: [String:Entry?]?

    public init(code: String? = nil, key: String? = nil, label: String? = nil, link: String? = nil, personId: String? = nil, content: PersonShareableContentResponse? = nil, data: [String:Entry?]? = nil) {
        self.code = code
        self.key = key
        self.label = label
        self.link = link
        self.personId = personId
        self.content = content
        self.data = data
    }

    public enum CodingKeys: String, CodingKey { 
        case code
        case key
        case label
        case link
        case personId = "person_id"
        case content
        case data
    }

}
