//
// PgpExtoleClientKeyResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PgpExtoleClientKeyResponse: Codable {

    public enum Algorithm: String, Codable { 
        case rsa = "RSA"
    }
    public var _id: String?
    public var name: String?
    public var email: String?
    public var algorithm: Algorithm?
    public var key: String?
    public var _description: String?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(_id: String? = nil, name: String? = nil, email: String? = nil, algorithm: Algorithm? = nil, key: String? = nil, _description: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self._id = _id
        self.name = name
        self.email = email
        self.algorithm = algorithm
        self.key = key
        self._description = _description
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case email
        case algorithm
        case key
        case _description = "description"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

}
