//
// RewardWebhookResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RewardWebhookResponse: Codable {

    public enum ModelType: String, Codable { 
        case reward = "REWARD"
        case generic = "GENERIC"
    }
    public var _id: String?
    public var name: String?
    public var type: ModelType?
    public var url: String?
    public var clientKeyId: String?
    public var tags: [String]?
    public var request: String?
    public var enabled: Bool?
    public var _description: String?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var defaultMethod: String?
    public var filters: [RewardWebhookFilterResponse]?

    public init(_id: String? = nil, name: String? = nil, type: ModelType? = nil, url: String? = nil, clientKeyId: String? = nil, tags: [String]? = nil, request: String? = nil, enabled: Bool? = nil, _description: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, defaultMethod: String? = nil, filters: [RewardWebhookFilterResponse]? = nil) {
        self._id = _id
        self.name = name
        self.type = type
        self.url = url
        self.clientKeyId = clientKeyId
        self.tags = tags
        self.request = request
        self.enabled = enabled
        self._description = _description
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.defaultMethod = defaultMethod
        self.filters = filters
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case type
        case url
        case clientKeyId = "client_key_id"
        case tags
        case request
        case enabled
        case _description = "description"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case defaultMethod = "default_method"
        case filters
    }

}
