//
// RuntimeEvaluatableHasPriorStepTriggerContextSetIdObject.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RuntimeEvaluatableHasPriorStepTriggerContextSetIdObject: Codable {

    public var expectedResultType: JavaType?

    public init(expectedResultType: JavaType? = nil) {
        self.expectedResultType = expectedResultType
    }


}
