//
// StepDataResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StepDataResponse: Codable {

    public enum Scope: String, Codable { 
        case _public = "PUBLIC"
        case _private = "PRIVATE"
        case client = "CLIENT"
    }
    public enum PersistTypes: String, Codable { 
        case journey = "JOURNEY"
        case profile = "PROFILE"
    }
    public var name: String?
    public var value: String?
    public var scope: Scope?
    public var dimension: Bool?
    public var persistTypes: [PersistTypes]?
    public var defaultValue: String?

    public init(name: String? = nil, value: String? = nil, scope: Scope? = nil, dimension: Bool? = nil, persistTypes: [PersistTypes]? = nil, defaultValue: String? = nil) {
        self.name = name
        self.value = value
        self.scope = scope
        self.dimension = dimension
        self.persistTypes = persistTypes
        self.defaultValue = defaultValue
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case value
        case scope
        case dimension
        case persistTypes = "persist_types"
        case defaultValue = "default_value"
    }

}
