//
// SubscriptionUserResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SubscriptionUserResponse: Codable {

    public var userId: String?
    public var email: String?
    public var firstName: String?
    public var lastName: String?

    public init(userId: String? = nil, email: String? = nil, firstName: String? = nil, lastName: String? = nil) {
        self.userId = userId
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
    }

    public enum CodingKeys: String, CodingKey { 
        case userId = "user_id"
        case email
        case firstName = "first_name"
        case lastName = "last_name"
    }

}
