//
// UserSubscriptionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserSubscriptionResponse: Codable {

    public enum FilteringLevel: String, Codable { 
        case all = "ALL"
        case some = "SOME"
        case noteworthy = "NOTEWORTHY"
        case _none = "NONE"
    }
    public var subscriptionId: String?
    public var havingAllTags: [String]?
    public var filteringLevel: FilteringLevel?
    public var channels: [SubscriptionChannelResponse]?

    public init(subscriptionId: String? = nil, havingAllTags: [String]? = nil, filteringLevel: FilteringLevel? = nil, channels: [SubscriptionChannelResponse]? = nil) {
        self.subscriptionId = subscriptionId
        self.havingAllTags = havingAllTags
        self.filteringLevel = filteringLevel
        self.channels = channels
    }

    public enum CodingKeys: String, CodingKey { 
        case subscriptionId = "subscription_id"
        case havingAllTags = "having_all_tags"
        case filteringLevel = "filtering_level"
        case channels
    }

}
