//
// BuiltCampaignFlowStepAppTypeResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BuiltCampaignFlowStepAppTypeResponse: Codable {

    public var name: String?

    public init(name: String? = nil) {
        self.name = name
    }


}
