//
// CampaignStepProcessor.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CampaignStepProcessor: Codable {

    public enum ModelType: String, Codable { 
        case _none = "NONE"
        case defaultRevenue = "DEFAULT_REVENUE"
    }
    public var type: ModelType?
    public var value: String?

    public init(type: ModelType? = nil, value: String? = nil) {
        self.type = type
        self.value = value
    }


}
