//
// CampaignPublishRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CampaignPublishRequest: Codable {

    public var message: String?
    public var launch: Bool?

    public init(message: String? = nil, launch: Bool? = nil) {
        self.message = message
        self.launch = launch
    }


}
