//
// CampaignDuplicateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CampaignDuplicateRequest: Codable {

    public var programLabel: String?
    public var message: String?
    public var _description: String?

    public init(programLabel: String? = nil, message: String? = nil, _description: String? = nil) {
        self.programLabel = programLabel
        self.message = message
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case programLabel = "program_label"
        case message
        case _description = "description"
    }

}
