//
// ClientResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ClientResponse: Codable {

    public enum ClientType: String, Codable { 
        case customer = "CUSTOMER"
        case exCustomer = "EX_CUSTOMER"
        case test = "TEST"
        case unclassified = "UNCLASSIFIED"
    }
    public var clientId: String?
    public var name: String?
    public var shortName: String?
    public var clientType: ClientType?
    public var version: Int?
    public var pod: String?
    public var coreSettings: ClientCoreSettingsV2Response?

    public init(clientId: String? = nil, name: String? = nil, shortName: String? = nil, clientType: ClientType? = nil, version: Int? = nil, pod: String? = nil, coreSettings: ClientCoreSettingsV2Response? = nil) {
        self.clientId = clientId
        self.name = name
        self.shortName = shortName
        self.clientType = clientType
        self.version = version
        self.pod = pod
        self.coreSettings = coreSettings
    }

    public enum CodingKeys: String, CodingKey { 
        case clientId = "client_id"
        case name
        case shortName = "short_name"
        case clientType = "client_type"
        case version
        case pod
        case coreSettings = "core_settings"
    }

}
