//
// ClientUpdateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ClientUpdateRequest: Codable {

    public enum ClientType: String, Codable { 
        case customer = "CUSTOMER"
        case exCustomer = "EX_CUSTOMER"
        case test = "TEST"
        case unclassified = "UNCLASSIFIED"
    }
    public var clientType: ClientType?
    public var pod: String?

    public init(clientType: ClientType? = nil, pod: String? = nil) {
        self.clientType = clientType
        self.pod = pod
    }

    public enum CodingKeys: String, CodingKey { 
        case clientType = "client_type"
        case pod
    }

}
