//
// ClientCoreSettingsV2Response.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ClientCoreSettingsV2Response: Codable {

    public var coreVersion: String?

    public init(coreVersion: String? = nil) {
        self.coreVersion = coreVersion
    }

    public enum CodingKeys: String, CodingKey { 
        case coreVersion = "core_version"
    }

}
