//
// EmailFireAsPersonIdentification.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EmailFireAsPersonIdentification: Codable {

    public enum PersonIdentificationType: String, Codable { 
        case email = "EMAIL"
        case personId = "PERSON_ID"
        case partnerUserId = "PARTNER_USER_ID"
        case partnerEventId = "PARTNER_EVENT_ID"
    }
    public var personIdentificationType: PersonIdentificationType?
    public var value: String?

    public init(personIdentificationType: PersonIdentificationType? = nil, value: String? = nil) {
        self.personIdentificationType = personIdentificationType
        self.value = value
    }

    public enum CodingKeys: String, CodingKey { 
        case personIdentificationType = "person_identification_type"
        case value
    }

}
