//
// HttpHeaderMatchPrehandlerConditionRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Condition that checks the event HTTP headers. */

public struct HttpHeaderMatchPrehandlerConditionRequest: Codable {

    public enum ModelType: String, Codable { 
        case eventNameMatch = "EVENT_NAME_MATCH"
        case httpHeaderMatch = "HTTP_HEADER_MATCH"
        case javascriptV1 = "JAVASCRIPT_V1"
    }
    public var type: ModelType
    /** Condition evaluates to true if any of these HTTP headers are present in the request. At least one HTTP header value should match. HTTP header names are not case sensitive. */
    public var httpHeaders: [String:[String]]

    public init(type: ModelType, httpHeaders: [String:[String]]) {
        self.type = type
        self.httpHeaders = httpHeaders
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case httpHeaders = "http_headers"
    }

}
