//
// IncentiveResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct IncentiveResponse: Codable {

    public var _id: String?
    public var qualityRules: [QualityRuleResponse]?
    public var rewardRules: [RewardRuleResponse]?
    public var transitionRules: [TransitionRuleResponse]?

    public init(_id: String? = nil, qualityRules: [QualityRuleResponse]? = nil, rewardRules: [RewardRuleResponse]? = nil, transitionRules: [TransitionRuleResponse]? = nil) {
        self._id = _id
        self.qualityRules = qualityRules
        self.rewardRules = rewardRules
        self.transitionRules = transitionRules
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case qualityRules = "quality_rules"
        case rewardRules = "reward_rules"
        case transitionRules = "transition_rules"
    }

}
