//
// JavascriptPrehandlerConditionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Condition represented by Javascript. It evaluates to true if the javascript returns true. */

public struct JavascriptPrehandlerConditionResponse: Codable {

    public enum ModelType: String, Codable { 
        case eventNameMatch = "EVENT_NAME_MATCH"
        case httpHeaderMatch = "HTTP_HEADER_MATCH"
        case javascriptV1 = "JAVASCRIPT_V1"
    }
    public var _id: String?
    public var type: ModelType?
    public var javascript: String?

    public init(_id: String? = nil, type: ModelType? = nil, javascript: String? = nil) {
        self._id = _id
        self.type = type
        self.javascript = javascript
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case type
        case javascript
    }

}
