//
// JavascriptPrehandlerActionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Action represented by Javascript that can change the event. */

public struct JavascriptPrehandlerActionResponse: Codable {

    public enum ModelType: String, Codable { 
        case setData = "SET_DATA"
        case setSandbox = "SET_SANDBOX"
        case mapDataAttributes = "MAP_DATA_ATTRIBUTES"
        case javascriptV1 = "JAVASCRIPT_V1"
    }
    public var _id: String?
    public var type: ModelType?
    public var javascript: String?

    public init(_id: String? = nil, type: ModelType? = nil, javascript: String? = nil) {
        self._id = _id
        self.type = type
        self.javascript = javascript
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case type
        case javascript
    }

}
