//
// MapDataAttributesPrehandlerActionRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Action that modifies the event data based on data mappers attributes. */

public struct MapDataAttributesPrehandlerActionRequest: Codable {

    public enum ModelType: String, Codable { 
        case setData = "SET_DATA"
        case setSandbox = "SET_SANDBOX"
        case mapDataAttributes = "MAP_DATA_ATTRIBUTES"
        case javascriptV1 = "JAVASCRIPT_V1"
    }
    public var type: ModelType
    public var dataAttributeMappings: [DataAttributeMapping]

    public init(type: ModelType, dataAttributeMappings: [DataAttributeMapping]) {
        self.type = type
        self.dataAttributeMappings = dataAttributeMappings
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case dataAttributeMappings = "data_attribute_mappings"
    }

}
