//
// PersonStepResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PersonStepResponse: Codable {

    public enum Quality: String, Codable { 
        case high = "HIGH"
        case low = "LOW"
        case _none = "NONE"
    }
    public var _id: String?
    public var campaignId: String?
    public var programLabel: String?
    public var container: String?
    public var stepName: String?
    public var eventId: String?
    public var eventDate: Date?
    public var value: String?
    public var partnerEventId: PartnerEventIdResponse?
    public var quality: Quality?
    public var data: [PersonDataResponse]?

    public init(_id: String? = nil, campaignId: String? = nil, programLabel: String? = nil, container: String? = nil, stepName: String? = nil, eventId: String? = nil, eventDate: Date? = nil, value: String? = nil, partnerEventId: PartnerEventIdResponse? = nil, quality: Quality? = nil, data: [PersonDataResponse]? = nil) {
        self._id = _id
        self.campaignId = campaignId
        self.programLabel = programLabel
        self.container = container
        self.stepName = stepName
        self.eventId = eventId
        self.eventDate = eventDate
        self.value = value
        self.partnerEventId = partnerEventId
        self.quality = quality
        self.data = data
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case campaignId = "campaign_id"
        case programLabel = "program_label"
        case container
        case stepName = "step_name"
        case eventId = "event_id"
        case eventDate = "event_date"
        case value
        case partnerEventId = "partner_event_id"
        case quality
        case data
    }

}
