//
// PersonStatsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PersonStatsResponse: Codable {

    public var aov: String?
    public var ltv: String?
    public var activities: Int64?
    public var transactions: Int64?
    public var conversions: Int64?

    public init(aov: String? = nil, ltv: String? = nil, activities: Int64? = nil, transactions: Int64? = nil, conversions: Int64? = nil) {
        self.aov = aov
        self.ltv = ltv
        self.activities = activities
        self.transactions = transactions
        self.conversions = conversions
    }


}
