//
// PersonLocaleResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PersonLocaleResponse: Codable {

    public var lastBrowser: String?
    public var userSpecified: String?

    public init(lastBrowser: String? = nil, userSpecified: String? = nil) {
        self.lastBrowser = lastBrowser
        self.userSpecified = userSpecified
    }

    public enum CodingKeys: String, CodingKey { 
        case lastBrowser = "last_browser"
        case userSpecified = "user_specified"
    }

}
