//
// PersonShareableContentResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PersonShareableContentResponse: Codable {

    public var partnerContentId: String?
    public var title: String?
    public var imageUrl: String?
    public var _description: String?
    public var url: String?

    public init(partnerContentId: String? = nil, title: String? = nil, imageUrl: String? = nil, _description: String? = nil, url: String? = nil) {
        self.partnerContentId = partnerContentId
        self.title = title
        self.imageUrl = imageUrl
        self._description = _description
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case partnerContentId = "partner_content_id"
        case title
        case imageUrl = "image_url"
        case _description = "description"
        case url
    }

}
