//
// PersonDataResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PersonDataResponse: Codable {

    public enum Scope: String, Codable { 
        case _public = "PUBLIC"
        case _private = "PRIVATE"
    }
    public var name: String?
    public var scope: Scope?
    public var value: String?

    public init(name: String? = nil, scope: Scope? = nil, value: String? = nil) {
        self.name = name
        self.scope = scope
        self.value = value
    }


}
