//
// PgpExtoleClientKeyCreateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PgpExtoleClientKeyCreateRequest: Codable {

    public enum Algorithm: String, Codable { 
        case rsa = "RSA"
    }
    public var name: String?
    public var email: String?
    public var algorithm: Algorithm?
    public var key: String?
    public var _description: String?

    public init(name: String? = nil, email: String? = nil, algorithm: Algorithm? = nil, key: String? = nil, _description: String? = nil) {
        self.name = name
        self.email = email
        self.algorithm = algorithm
        self.key = key
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case email
        case algorithm
        case key
        case _description = "description"
    }

}
