//
// ProfileBlockResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProfileBlockResponse: Codable {

    public var reason: String?
    public var date: Date?

    public init(reason: String? = nil, date: Date? = nil) {
        self.reason = reason
        self.date = date
    }


}
