//
// RequestContextResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RequestContextResponse: Codable {

    public var ip: String?
    public var deviceId: String?
    public var createdAt: Date?
    public var country: Country?
    public var state: State?
    public var city: City?
    public var location: Location?

    public init(ip: String? = nil, deviceId: String? = nil, createdAt: Date? = nil, country: Country? = nil, state: State? = nil, city: City? = nil, location: Location? = nil) {
        self.ip = ip
        self.deviceId = deviceId
        self.createdAt = createdAt
        self.country = country
        self.state = state
        self.city = city
        self.location = location
    }

    public enum CodingKeys: String, CodingKey { 
        case ip
        case deviceId = "device_id"
        case createdAt = "created_at"
        case country
        case state
        case city
        case location
    }

}
