//
// RewardRuleExpression.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RewardRuleExpression: Codable {

    public enum ModelType: String, Codable { 
        case spel = "SPEL"
        case js = "JS"
    }
    public var value: String
    public var type: ModelType

    public init(value: String, type: ModelType) {
        self.value = value
        self.type = type
    }


}
