//
// SetDataPrehandlerActionRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Action that modifies the event data. */

public struct SetDataPrehandlerActionRequest: Codable {

    public enum ModelType: String, Codable { 
        case setData = "SET_DATA"
        case setSandbox = "SET_SANDBOX"
        case mapDataAttributes = "MAP_DATA_ATTRIBUTES"
        case javascriptV1 = "JAVASCRIPT_V1"
    }
    public var type: ModelType
    /** Data to be set to the event. Data names (keys) are not case sensitive. */
    public var data: [String:String]?
    /** Default data to be set to the event. Only data (keys) that are not already present in the event will be set. Data names (keys) are not case sensitive. */
    public var defaultData: [String:String]?
    /** Names (keys) of the data that should be removed from the event. Data names (keys) are not case sensitive. */
    public var deleteData: [String]?

    public init(type: ModelType, data: [String:String]? = nil, defaultData: [String:String]? = nil, deleteData: [String]? = nil) {
        self.type = type
        self.data = data
        self.defaultData = defaultData
        self.deleteData = deleteData
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case data
        case defaultData = "default_data"
        case deleteData = "delete_data"
    }

}
