//
// SetDataPrehandlerActionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Action that modifies the event data. */

public struct SetDataPrehandlerActionResponse: Codable {

    public enum ModelType: String, Codable { 
        case setData = "SET_DATA"
        case setSandbox = "SET_SANDBOX"
        case mapDataAttributes = "MAP_DATA_ATTRIBUTES"
        case javascriptV1 = "JAVASCRIPT_V1"
    }
    public var _id: String?
    public var type: ModelType?
    public var data: [String:String]?
    public var defaultData: [String:String]?
    public var deleteData: [String]?

    public init(_id: String? = nil, type: ModelType? = nil, data: [String:String]? = nil, defaultData: [String:String]? = nil, deleteData: [String]? = nil) {
        self._id = _id
        self.type = type
        self.data = data
        self.defaultData = defaultData
        self.deleteData = deleteData
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case type
        case data
        case defaultData = "default_data"
        case deleteData = "delete_data"
    }

}
