//
// SlackSubscriptionChannelRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SlackSubscriptionChannelRequest: Codable {

    public enum ModelType: String, Codable { 
        case slack = "SLACK"
        case email = "EMAIL"
        case extoleClientSlack = "EXTOLE_CLIENT_SLACK"
    }
    public var type: ModelType?
    public var webhookUrl: String?

    public init(type: ModelType? = nil, webhookUrl: String? = nil) {
        self.type = type
        self.webhookUrl = webhookUrl
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case webhookUrl = "webhook_url"
    }

}
