//
// UserSubscriptionRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserSubscriptionRequest: Codable {

    public enum FilteringLevel: String, Codable { 
        case all = "ALL"
        case some = "SOME"
        case noteworthy = "NOTEWORTHY"
        case _none = "NONE"
    }
    public var havingAllTags: [String]
    public var filteringLevel: FilteringLevel?
    public var channels: [SubscriptionChannelRequest]?

    public init(havingAllTags: [String], filteringLevel: FilteringLevel? = nil, channels: [SubscriptionChannelRequest]? = nil) {
        self.havingAllTags = havingAllTags
        self.filteringLevel = filteringLevel
        self.channels = channels
    }

    public enum CodingKeys: String, CodingKey { 
        case havingAllTags = "having_all_tags"
        case filteringLevel = "filtering_level"
        case channels
    }

}
